version: 1
formatters:
  simple:
    format: "%(asctime)s,%(msecs)03d | %(levelname)10s | %(name)10s | \n%(message)s"
    datefmt: "%Y-%m-%d %H-%M-%S"
  detail:
    format: "%(asctime)s,%(msecs)03d | %(levelname)10s | %(name)10s | %(filename)10s %(lineno)03d | \n%(message)s"
    datefmt: "%Y-%m-%d %H-%M-%S"
  complex:
    format: "%(asctime)s,%(msecs)03d | %(levelname)10s | %(name)10s | P%(process)06d,T%(thread)06d,%(taskName)s | %(filename)10s %(lineno)03d | \n%(message)s"
    datefmt: "%Y-%m-%d %H-%M-%S"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  websocketsDayFile:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: detail
    filename: log/websockets_day.log
    when: D
    encoding: utf-8
  dayRotatingFile:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: detail
    filename: log/day.log
    when: D
    encoding: utf-8
  weekRotatingFile:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: detail
    filename: log/week.log
    when: D
    encoding: utf-8
loggers:
  websockets:
    level: DEBUG
    handlers: [console, websocketsDayFile]
    propagate: no
  WsPublic:
    level: INFO
    handlers: [console, dayRotatingFile]
    propagate: no
  WsPrivate:
    level: DEBUG
    handlers: [console, dayRotatingFile]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
